name: simple echo template
description: "A template to echo from inputs"

inputs:
  message:
    description: 'Message to print'
    required: true

runs:
  using: "composite"
  steps:
    - name: echo github ref
      shell: bash
      run: |
        echo "${{ github.ref }} "
    - name: Set env vars for main
      shell: bash
      run: |
        echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
      if: startsWith(github.ref, 'refs/heads/main')
    - name: Set env vars for other branch
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ github.event.inputs.from_branch }}" >> "$GITHUB_ENV"
      if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
    - name: echo
      shell: bash
      run: |
        echo "${{ inputs.message }} ${{env.IMAGE_TAG}}"
