name: simple echo template
description: "A template to echo from inputs"

inputs:
  message:
    description: 'Message to print'
    required: true

runs:
  using: "composite"
  env:
      PUSH: true
  steps:
    - name: set push
      shell: bash
      run: |
        echo "PUSH=false" >> "$GITHUB_ENV"
      if: ${{ !startsWith(github.event.pull_request.head.repo.full_name, 'CIROH-UA') }}
    - name: echo branch name
      shell: bash
      run: |
        echo ${GITHUB_REF#refs/heads/}
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
    - name: Set env vars for main
      shell: bash
      run: |
        echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
      if: startsWith(github.ref, 'refs/heads/main')
    - name: Set env vars for other branch
      shell: bash
      run: |
        echo "IMAGE_TAG=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
      if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
    - name: echo
      shell: bash
      run: |
        echo "${{ inputs.message }} ${{env.IMAGE_TAG}}"
        echo "${{env.PUSH}}"
