name: Build and push Docker image manually

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
          
      - name: Create Cache and Builder for Buildx
        run: |
            docker buildx create --use --name mybuilder --node mybuilder

      - name: Build and Cache Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/x86_64
          tags: |
            awiciroh/echo-hello:latest
          builder: mybuilder
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
