name: First workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: deploy
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name}}
      - run: echo "base branch is $GITHUB_REF_NAME ${{inputs.tag_name}}"
