name: First workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v4
      - run: echo "base branch is $GITHUB_REF_NAME ${{inputs.tag_name}} var ${{var.TAG_NAME}}"
