name: Grand Parent workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string
  workflow_call:
    inputs:
      slack-webhook-url:
        description: 'Slack webhook url'
        required: true
        type: string

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: echo "${{ inputs.slack-webhook-url }}"
      - name: send slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
             "text": "GitHub Action build result (test) : success"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
