name: Parent workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: [fourth]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: send slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
             "text": "GitHub Action build result (test) : success"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  on-failure:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - name: send slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
             "text": "GitHub Action build result (test) : failure"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
