name: Hello Workflow
on:
  workflow_dispatch:

jobs:
  build:
    name: Run hello action
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v4
      - name: Set env vars for main
        run: |
          echo "IMAGE_TAG=main" >> "$GITHUB_ENV"
      - name: Set env vars for other branch
        run: |
          echo "IMAGE_TAG=other" >> "$GITHUB_ENV"
        if: startsWith(github.ref, 'refs/remotes/origin/main')
      - name: echo
        run: |
          echo "${{env.IMAGE_TAG}}"
