name: Hello Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TEST_TAG: user/app:test

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      push: ${{ steps.setmain.outputs.push }}
    steps:
      - id: setmain
        run: echo "push=true" >> "$GITHUB_OUTPUT"
        if: startsWith(github.ref, 'refs/heads/main')
      - run: echo " tag ${{env.TEST_TAG}}"
  docker:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: actions/checkout@v4
      - name: echo docker token
        if: always()
        run: |
          echo "${{ secrets.DOCKER_AUTH_TOKEN }}"
      - name: Build a Docker image
        uses: ./.github/action_templates/build
        with:
          image-name: ${{ env.TEST_TAG }}
      #- name: Test
      #  run: |
      #    docker run --rm ${{ env.TEST_TAG }}
      - name: Remove Image
        run: |
          docker image rm ${{ env.TEST_TAG }} -f
