name: Hello Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TEST_TAG: user/app:test

jobs:
  docker:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: actions/checkout@v4
      - name: echo docker token
        if: always()
        run: |
          echo "${{ secrets.DOCKER_AUTH_TOKEN }}"
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Remove Image
        run: |
          docker image rm ${{ env.TEST_TAG }} -f
