name: Hello Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Run hello action
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v4
      - name: echo github ref
        run: |
          echo "${{ github.ref }} "
      - name: echo docker token
        if: always()
        run: |
          echo "${{ secrets.DOCKER_AUTH_TOKEN }}"
      - name: echo hello
        run: |
          echo "hello"
          echo "${{github.event.pull_request.base.repo.full_name}}"
          echo "${{github.event.pull_request.head.repo.full_name}}"
        if: ${{ !startsWith(github.event.pull_request.head.repo.full_name, 'CIROH-UA') }}
      #- name: Set env vars for main
      #  run: |
      #    echo "IMAGE_TAG=main" >> "$GITHUB_ENV"
      #- name: Set env vars for other branch
      #  run: |
      #    echo "IMAGE_TAG=other" >> "$GITHUB_ENV"
      #  if: startsWith(github.ref, 'refs/heads/main')
      #- name: echo
      #  run: |
      #    echo "${{env.IMAGE_TAG}}"
