name: Parent workflow
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string
env:
  TAG_NAME: ${{ github.event.inputs.tag_name }}

jobs:
  first:
    uses: ./.github/workflows/first.yml
    with:
      tag_name: latest-arm
  second:
    needs: first
    uses: ./.github/workflows/second.yml
    with:
      tag_name: $TAG_NAME
  third:
    needs: second
    uses: ./.github/workflows/third.yml
  fourth:
    needs: third
    uses: ./.github/workflows/fourth.yml
