name: Parent workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string
  workflow_call:

jobs:
  first:
    uses: ./.github/workflows/first.yml
    with:
      tag_name: ${{inputs.tag_name}}
  second:
    needs: first
    uses: ./.github/workflows/second.yml
    with:
      tag_name: ${{inputs.tag_name}}
  third:
    needs: second
    uses: ./.github/workflows/third.yml
  fourth:
    needs: third
    uses: ./.github/workflows/fourth.yml
  fifth:
    needs: fourth
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: echo "result=success" >> "$GITHUB_ENV"
  slack:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [first, second, third, fourth, fifth]
    steps:
      - env:
          OUTPUT: ${{needs.fifth.outputs.output1}}
        run: echo "$OUTPUT"
      - name: Set env JOBSTATUS
        run: |
          if [[ ${{needs.fifth.outputs.output1}} == 'success' ]]; then
              echo "JOBSTATUS=success" >> "$GITHUB_ENV"
          else
              echo "JOBSTATUS=failure" >> "$GITHUB_ENV"
          fi
      - run: echo "$JOBSTATUS"
      - run: echo "$result"
      - name: deploy
        uses: actions/checkout@v2
      - name: Publish slack message
        if: always()
        uses: ./.github/action_templates/slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job-status: ${{ env.JOBSTATUS }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
          head_commit_url: ${{ github.event.head_commit.url }}
