name: Parent workflow
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  pull_request:
    types: [opened, reopened, edited, labeled]
    paths:
      - docker/**
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string

jobs:
  first:
    uses: ./.github/workflows/first.yml
    with:
      tag_name: ${{inputs.tag_name}}
  second:
    needs: first
    uses: ./.github/workflows/second.yml
    with:
      tag_name: ${{inputs.tag_name}}
  third:
    needs: second
    uses: ./.github/workflows/third.yml
  fourth:
    needs: third
    uses: ./.github/workflows/fourth.yml
