name: Parent workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string
  workflow_call:

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: slack message
        uses: ./.github/workflows/slack.yml
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job-status: ${{ job.status }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
          head_commit_url: ${{ github.event.head_commit.url }}
  first:
    uses: ./.github/workflows/first.yml
    with:
      tag_name: ${{inputs.tag_name}}
  second:
    needs: first
    uses: ./.github/workflows/second.yml
    with:
      tag_name: ${{inputs.tag_name}}
  third:
    needs: second
    uses: ./.github/workflows/third.yml
  fourth:
    needs: third
    uses: ./.github/workflows/fourth.yml
