name: Parent workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest-arm'
        type: string
  workflow_call:

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: send slack message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
             "text": "GitHub Action build result (test) : ${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  first:
    uses: ./.github/workflows/first.yml
    with:
      tag_name: ${{inputs.tag_name}}
  second:
    needs: first
    uses: ./.github/workflows/second.yml
    with:
      tag_name: ${{inputs.tag_name}}
  third:
    needs: second
    uses: ./.github/workflows/third.yml
  fourth:
    needs: third
    uses: ./.github/workflows/fourth.yml
