name: Parent workflow
on:
  workflow_dispatch:

jobs:
  first:
    uses: ./.github/workflows/first.yml
  second:
    needs: first
    uses: ./.github/workflows/second.yml
  third:
    needs: second
    uses: ./.github/workflows/third.yml
  fourth:
    needs: third
    uses: ./.github/workflows/fourth.yml
