name: "tagged-release"

on:
  push:
    paths:
      - 'version.txt'
  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"
          echo "github ref: ${{github.ref}}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read README.md
        id: package
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: version.txt
      - name: Echo version.txt
        run: echo "${{ steps.package.outputs.content }}"
      - name: Generate version
        id: version
        run: echo "::set-output name=VERSION::${{ steps.package.outputs.content }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package.outputs.content }}
          release_name: Release ${{ steps.package.outputs.content }}
          draft: false
          prerelease: false
