name: Create Tag, Release, Branch, and Trigger Workflow

on:
  push:
    paths:
      - 'version.txt'

jobs:
  create-tag-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version
        id: get-version
        run: |
          VERSION=$(cat version.txt)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "branch_name=release-${VERSION}" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v${{ steps.get-version.outputs.version }}
          git push origin v${{ steps.get-version.outputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          release_name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false

      - name: Create branch
        run: |
          git checkout -b ${{ steps.get-version.outputs.branch_name }}
          git push -u origin ${{ steps.get-version.outputs.branch_name }}

      - name: Trigger Another Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'another-workflow.yml',
              ref: '${{ steps.get-version.outputs.branch_name }}'
            })
