name: Test Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner}}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest-xlarge]
    steps:
      - name: first
        run: echo "this is first"
