name: Third workflow
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name}}
      - run: echo "base branch is $GITHUB_REF_NAME"
